package main

type FileTemplate struct {
	Name    string
	Content string
}

var files = []FileTemplate{
	{
		Name:    "{{.Name}}.png",
		Content: "empty image",
	},
	{
		Name:    ".gitignore",
		Content: "dist",
	},
	{
		Name: "Makefile",
		Content: `CHECK_PROGRAM := $(shell which plugin_api 2>/dev/null)
ifeq ($(CHECK_PROGRAM),)
   $(error "plugin_api not found,install cmd: go install github.com/medianexapp/plugin_api/cmd/plugin_api@latest")
endif
build:
			plugin_api build
`,
	},
	{
		Name: "plugin.go",
		Content: `// Code generated by plugin_api. DO NOT EDIT.
//go:build wasip1

package main

import (
			"github.com/medianexapp/plugin_api"
)

func init() {
			plugin_api.RegistryPlugin(NewPluginImpl())
}

func main() {}
`,
	},

	{
		Name: "plugin.toml",
		Content: `id = "{{.Name}}"
name = "{{.Name}}"
desc = "{{.Name}} plugin desc"
icon = "{{.Name}}.png"
author = ["{{.Author}}"]
version = "v0.0.1"
changelog = ["{{.Name}} plugin init"]
`,
	},
	{
		Name: "plugin_impl.go",
		Content: `id = "{{.Name}}"
name = "{{.Name}}"
desc = "{{.Name}} plugin desc"
icon = "{{.Name}}.png"
author = ["{{.Author}}"]
version = "v0.0.1"
changelog = ["{{.Name}} plugin init"]
`,
	},
}
