syntax = "proto3";

package plugin;
option  go_package = "github.com/medianexapp/plugin_api/plugin;plugin";
import "plugin/wrappers.proto";

enum PluginType {
    PLUGIN_TYPE_UNSPECIFIED = 0;
    PLUGIN_TYPE_FILE_SYSTEM = 1;  // plugin connect file system, like smb,webdav,cloud driver,this is default plugin type
    PLUGIN_TYPE_MEDIA       = 2;  // plugin connect media server,like plex,emby,youtube
}

message Formdata {
    message FormItem {
        string name = 1;
        oneof  Value {
            plugin.DoubleValue        double_value         = 2;
            plugin.Int64Value         int64_value          = 3;
            plugin.BoolValue          bool_value           = 4;
            plugin.StringValue        string_value         = 5;
            plugin.ObscureStringValue obscure_string_value = 6;
            plugin.DirPathValue       dir_path_value       = 7;
            plugin.FilePathValue      file_path_value      = 8;
        }
        repeated FormItem enum_values = 10;  // for dropdown widget
    }
    repeated FormItem form_items = 11;
}

message Scanqrcode {
    bytes  qrcode_image         = 1;  // qrcode image bytes
    string qrcode_image_param   = 2;  // qrcode image some param
    uint64 qrcode_expire_time   = 3;  // qrcode expire time
    string qrcode_image_url     = 4;  // qrcode image url
    string qrcode_image_content = 5;  // qrcode content
}

message Callback {
    string callback_url       = 1;  // callback url
    string callback_url_param = 2;  // param for call back url
    string callback_url_data  = 3;  // url callback data
}

message Refresh {
    AuthData auth_data = 1;
}

message AuthMethod {
    oneof method {
        Formdata   formdata   = 1;
        Scanqrcode scanqrcode = 2;
        Callback   callback   = 3;
        Refresh    refresh    = 4;
    }
    string help_doc_url = 5;  // help document
}

message Auth {
    // valid auth methods
    repeated AuthMethod auth_methods = 1;
}

message FileEntry {
    enum FileType {
        FileTypeUNSPECIFIED = 0;
        FileTypeDir         = 1;
        FileTypeFile        = 2;
        FileTypeLink        = 3;
    }
    string   name      = 1;
    FileType file_type = 2;
    uint64   size      = 3;
    bytes    raw_data  = 4;

    uint64 created_time  = 10;
    uint64 modified_time = 11;
    uint64 accessed_time = 12;
}

message DirEntry {
    repeated FileEntry file_entries = 1;
    uint64             page_size    = 2;
    string             dir_page_key = 10;
}

message GetDirEntryRequest {
    string path = 1;
    uint64 page = 2;
    // default page_size is 100,if this not for you,change is on DirEntry.PageSize
    uint64 page_size = 3;

    FileEntry file_entry   = 10;
    string    dir_page_key = 12;
}

message GetFileResourceRequest {
    string    file_path  = 1;
    FileEntry file_entry = 10;
    bool      is_media   = 11;  // media file

    // media Item play item id
    string media_play_id = 20;
}

message FileResource {
    // video display VideoResolution
    enum Resolution {
        ResolutionUNSPECIFIED = 0;
        Original              = 1;  // Origin
        LD                    = 2;  // 360P high defintion
        SD                    = 3;  // 480P high defintion
        HD                    = 4;  // 720P high defintion
        FHD                   = 5;  // 1080P full high defintion
        QHD                   = 6;  // 2K  quad high defintion
        UHD                   = 7;  // 4K ultra high defintion
    }
    enum ResourceType {
        ResourceTypeUNSPECIFIED = 0;
        Video                   = 1;
        Subtitle                = 2;
        Audio                   = 3;
    }

    message FileResourceData {
        string              url                  = 1;
        Resolution          resolution           = 2;
        uint64              expire_time          = 3;
        ResourceType        resource_type        = 4;
        string              title                = 5;
        map<string, string> header               = 6;
        uint64              size                 = 7;   // file total size
        bool                proxy                = 8;   // proxy
        uint64              proxy_chunk_size     = 9;   // url proxy size
        uint64              proxy_chunk_parallel = 10;  // url proxy parallel
    }
    repeated FileResourceData file_resource_data = 1;
}

message AuthData {
    bytes  auth_data_bytes        = 1;
    uint64 auth_data_expired_time = 2;
}

// oauth config
message OauthConfig {
    string          client_id     = 1;
    string          client_secret = 2;
    string          redirect_uri  = 3;
    repeated string scopes        = 4;
    string          auth_url      = 5;
    string          qrcode_url    = 6;

    string token_url = 10;
    // json POST application/json
    // form POST application/x-www-form-urlencoded
    // uri GET
    string token_req_type = 11;
}

message Token {
    string token_type    = 1;
    string access_token  = 2;
    string refresh_token = 3;
    uint64 expires_in    = 4;
}

message PluginItem {
    string name     = 1;
    string value    = 2;
    string icon     = 3;  // icon url
    bool   disabled = 4;  // disable the item
}

// menu
message PluginMenu {
    PluginItem          menu     = 1;
    repeated PluginMenu sub_menu = 2;
}

message PluginMenus {
    repeated PluginMenu plugin_menus = 1;
}

message PluginFilterItems {
    message Filter {
        string              name  = 1;
        repeated PluginItem items = 2;
    }
    repeated Filter filters = 1;
}

// media item
message PluginMedia {
    string media_id = 1;  // media item id
    enum MediaType {
        MEDIA_UNSPECIFIED = 0;
        MEDIA_SERIES      = 1;
        MEDIA_INFO        = 2;
        MEDIA_PLAY_ITEM   = 3;
    }
    MediaType media_type      = 2;
    string    name            = 3;
    string    desc            = 4;
    string    parent_media_id = 5;
    // media info
    string          release_date      = 13;
    uint64          year              = 14;
    repeated string genres            = 15;  // media video genres for media Item info
    string          backdrop_url      = 16;  // media video backdrop image for media Item info
    string          poster_url        = 17;  // media video poster image for media Item info
    string          original_name     = 18;
    string          original_language = 19;
    enum CreditType {
        CreditUNSPECIFIED    = 0;
        CreditActor          = 1;  // Actor
        CreditCastDirecting  = 2;  // Directing
        CreditCastProduction = 3;  // Production
        CreditCastWriting    = 4;  // Writing
    }
    message Credit {
        CreditType credit_type = 1;  // credit type
        string     name        = 2;  // credit name
        string     profile_url = 3;
        string     character   = 4;
    }
    repeated Credit     credit   = 20;  // media credits
    map<string, string> metadata = 21;  // media metadata
    string              logo_url = 17;
    // media play item
    uint64 play_index = 30;  // play item indx
    uint64 duration   = 31;  // video duration unit: s
    string still_url  = 32;  // media video poster image for media Item play item

    string              play_item_url    = 33;
    map<string, string> play_item_header = 34;
}

message ListPluginMediaInfoRequest {
    PluginItem        menu        = 1;  // menu sub item
    PluginFilterItems filters     = 2;  // sub page filter
    string            search_name = 3;  // name search

    uint64 page      = 10;
    uint64 page_size = 11;
    string page_key  = 12;
}

message ListPluginMediaInfoResponse {
    repeated PluginMedia media_infos = 1;

    bool              support_search_name     = 10;
    PluginFilterItems all_plugin_filter_items = 11;  // sub page filter
    string            next_page_key           = 12;
}

message GetPluginMediaDetailRequest {
    string media_info_id = 1;
}

message GetPluginMediaDetailResponse {
    PluginMedia          media_series         = 1;
    PluginMedia          media_info           = 2;
    repeated PluginMedia media_items          = 3;
    repeated PluginMedia media_info_relations = 4;  // relation media info
}
